### ISSUE TITLE
Open circuit not really open?

### ISSUE THREAD

**Issue by feschmidt** [mgely/qucat#16]
The following circuit is evaluated fine (without me being able to tell if the result is correct; this is just to test the circuit drawings):
![image](https://user-images.githubusercontent.com/21104656/57536211-fc099400-7343-11e9-98b8-6506320da08b.png)
However, when I add a piece of wire to close the loop like this:
![image](https://user-images.githubusercontent.com/21104656/57536148-e1cfb600-7343-11e9-8c95-e74bfcc2fc61.png)
qucat returns a `ValueError: Analyzing an open circuit is impossible`, even though this circuit should be more closed than before?

**Comment by feschmidt** [comment]
These are the `.txt` files to recreate the bug
[felix_test_loops_broken.txt](https://github.com/mgely/qucat/files/3166989/felix_test_loops_broken.txt)
[felix_test_loops_working.txt](https://github.com/mgely/qucat/files/3166990/felix_test_loops_working.txt)

**Comment by gsteele13** [comment]
maybe also a suggestion on the wording of your error messages: 

"Your circuit appears to be open, analysis of open circuits is not supported by QuCAT"

And what do you mean by "open circuit"? Do you have a precise definition for this?

**Comment by gsteele13** [comment]
Maybe something like: "To perform normal mode analysis, there should be no open nodes in the network" is whatyou mean?

**Comment by feschmidt** [comment]
What the additional wire is doing is to short-circuit the bottom-right junction. But then I would have expected a `ValueError: node_minus==node_plus`

**Comment by PiotrBenedysiuk** [comment]
This issue has to do with the addition of extra elements. The circuit below works:
![image](https://user-images.githubusercontent.com/17763835/57698164-3e3d1900-7655-11e9-8af8-ff2779a8a08a.png)

but if adding a resistor results in the 'ValueError: Analyzing an open circuit is impossible`:
![image](https://user-images.githubusercontent.com/17763835/57698249-7e9c9700-7655-11e9-9f80-f15aed25cd6b.png).

Weirdly enough changing the position of ground can fix the issue, as
![image](https://user-images.githubusercontent.com/17763835/57698358-c4595f80-7655-11e9-9401-87e62d6076f0.png)
works just fine.

**Comment by mgely** [comment]
> The following circuit is evaluated fine (without me being able to tell if the result is correct; this is just to test the circuit drawings):
> ![image](https://user-images.githubusercontent.com/21104656/57536211-fc099400-7343-11e9-98b8-6506320da08b.png)
> However, when I add a piece of wire to close the loop like this:
> ![image](https://user-images.githubusercontent.com/21104656/57536148-e1cfb600-7343-11e9-8c95-e74bfcc2fc61.png)
> qucat returns a `ValueError: Analyzing an open circuit is impossible`, even though this circuit should be more closed than before?

Both circuits actually have shorts in them, in the first circuit, QuCAT does "something" but it's a false-positive, it's computing rubbish. In the second the short circuit leads to an open being detected, but the origin of the problem lies in the short.

**Comment by mgely** [comment]
> but if adding a resistor results in the 'ValueError: Analyzing an open circuit is impossible`:
> ![image](https://user-images.githubusercontent.com/17763835/57698249-7e9c9700-7655-11e9-9f80-f15aed25cd6b.png).

Again, the issue in your circuit has to do with the wire shorting the parallel connection of a junction and capacitor on the left.

**Comment by mgely** [comment]
All these issues were associated with short-circuits, which are now detected following commit 53b4853ce0143ddda362dc88ec78471ed33b46cc and raise an error.

> Maybe something like: "To perform normal mode analysis, there should be no open nodes in the network" is whatyou mean?
@gsteele13 Makes a good point, the errors now read
``Your circuit appears to be open making the analysis impossible``
or
``Your circuit appears to be shorted making the analysis impossible``

> What the additional wire is doing is to short-circuit the bottom-right junction. But then I would have expected a `ValueError: node_minus==node_plus`
@feschmidt 
This is now implemented and this situation raises a ValueError:
``Your circuit appears to be shorted making the analysis impossible``
