### ISSUE TITLE
Make keystroke for component rotation more obvious

### ISSUE THREAD

**Issue by mgely** [mgely/qucat#17]

**Comment by PiotrBenedysiuk** [comment]
The obviousness needs to start somewhere - what is the keystroke to begin with?

**Comment by mgely** [comment]
Until you use the keystroke to rotate, which are the arrow keys, a message will appear on the top left of the Window. It is unfortunately too small at the moment

**Comment by mgely** [comment]
Solved in d4302db2485e96d29c331ca5ba68874aa3c86c9a

**Comment by mgely** [comment]
Rotate button is now visible in the "Edit" menu, and when right clicking on one or a group of components
