### ISSUE TITLE
GUI issues on mac

### ISSUE THREAD

**Issue by feschmidt** [mgely/qucat#18]
**Operating system: MacOS HighSierra 10.13.6**

**Possibly related issues:**
- https://github.com/mgely/qucat/issues/2
- https://github.com/mgely/qucat/issues/6

**I have the following issues on my mac:**
- the writing is too small, see screenshot
- the GUI closes unexpectedly when trying to scroll using two fingers
- except for the wires and capacitors, none of the circuit element icons show up. They appear to have been placed with the corresponding values and are drawn in the jupyter seem, but don't appear in the GUI

![Bildschirmfoto 2019-05-13 um 09 05 50](https://user-images.githubusercontent.com/21104656/57602103-875e7180-755e-11e9-8643-902e3f8371af.png)
![Bildschirmfoto 2019-05-13 um 09 13 57](https://user-images.githubusercontent.com/21104656/57602484-85e17900-755f-11e9-8e41-42684b2f5668.png)
![Bildschirmfoto 2019-05-13 um 09 14 05](https://user-images.githubusercontent.com/21104656/57602486-85e17900-755f-11e9-8e78-86ce178aca0d.png)

**Text file containing the circuit:**
[felix-test-shorting.txt](https://github.com/mgely/qucat/files/3171517/felix-test-shorting.txt)

**Comment by mgely** [comment]
I have just tested the mentioned features on a more recent version of the mac OS (Mojave 10.14.3), and everything works fine... 
I will now start debugging on HighSierra 10.13.6

**Comment by mgely** [comment]
On HighSierra, Re-Center also does not work (ctrl+R)

**Comment by mgely** [comment]
Font problem solved in 501a86cd1de275202a52cdebe50ad6c7df95c7f5
Other problems moved to their own issue, see 
 - scrolling issue: #28 
 - components not showing: #30

**Comment by mgely** [comment]
All issues are now resolved
