### ISSUE TITLE
Current direction in normal modes is wrong.

### ISSUE THREAD

**Issue by PiotrBenedysiuk** [mgely/qucat#20]
In some circuits the direction of the current is wrong (in this example the current over the capacitator and the inductor should point in the opposite direction):
![image](https://user-images.githubusercontent.com/17763835/57765091-160cf300-7705-11e9-94b8-c9f5f369816b.png).

The voltage will have a minus sign at the corresponding branch too.
[Simple_LC.txt](https://github.com/mgely/qucat/files/3181953/Simple_LC.txt)

**Comment by mgely** [comment]
Solved in 4c660bb32d6267f4707f218ad455d4f7e49fbaa2

Result is now:

![image](https://user-images.githubusercontent.com/10977359/58029022-0bdf6000-7b1c-11e9-8385-13a47946c57a.png)

Also note that 16.4+26.5=42.9 so current is conserved
